site_name: OpenSensorHub
site_description: 'Software for building smart sensor networks'
repo_url: https://github.com/opensensorhub/
copyright: '© Copyright 2015 Sensia Software LLC'
google_analytics: ['UA-36723568-3', 'opensensorhub.org']

pages:
- Introduction: index.md
- Getting Started:
    - Download: download.md
    - Installation: install.md
- User Documentation:
    - Introduction: user-guide.md
    - SOS Service: swe-services/sos.md
- Developer Documentation:
    - Introduction: dev-guide.md
    - Architecture: architecture.md
    - Javadoc: apidocs/index.html
- Tutorials:
    - Adding New Modules: tutos/adding-new-modules.md
    - Your First Sensor: tutos/your-first-sensor.md
- Core APIs:
    - Introduction: core-apis/index.md
    - SensorML API: core-apis/sensorml-api.md
    - Sensor API: core-apis/sensor-api.md
    - Sensor Net API: core-apis/sensornet-api.md
- License: license.md
  
#theme: readthedocs
theme_dir: 'custom_theme'
dev_addr: 0.0.0.0:8000

