site_name: OpenSensorHub
site_description: 'Software for building smart sensor networks'
repo_url: https://github.com/opensensorhub/
copyright: '© Copyright 2015 Sensia Software LLC'
google_analytics: ['UA-36723568-3', 'opensensorhub.org']

pages:
- Introduction: index.md
- Getting Started:
    - Download: download.md
    - Installation: install.md
- User Documentation:
    - Introduction: user/user-guide.md
    - Supported Protocols: user/protocols.md
    - Web Admin: user/web-admin.md
    - SOS Interface:
         - Introduction: user/sos/intro.md
         - Retrieving Data: user/sos/get-data.md
         - Temporal Filtering : user/sos/time-filter.md
         - Spatial Filtering : user/sos/spatial-filter.md
         - Filtering by Feature : user/sos/foi-filter.md
         - WebSocket Support: user/sos/websocket.md
         - Interconnecting SensorHubs: user/sos/interconnect.md
    - SPS Interface: user/sps/intro.md
    - Demo Android App: user/android-app.md
- Developer Documentation:
    - Developer's Guide: dev/dev-guide.md
    - Architecture: dev/architecture.md
    - Core APIs:
         - Introduction: dev/core-apis/index.md
         - SensorML API: dev/core-apis/sensorml-api.md
         - Sensor API: dev/core-apis/sensor-api.md
         - Sensor Network API: dev/core-apis/sensornet-api.md
    - Javadoc: apidocs/index.html
    - Android Support: dev/android.md
    - Arduino Support: dev/arduino.md
- Tutorials:
    - Adding New Modules: tutos/adding-new-modules.md
    - Your First Sensor: tutos/your-first-sensor.md

- License: license.md
  
#theme: readthedocs
theme_dir: 'custom_theme'
dev_addr: 0.0.0.0:8000

